-- edw_prod_dbo.bbb_om_table4_backlog_ebs_v source

CREATE OR REPLACE VIEW edw_prod_dbo.bbb_om_table4_backlog_ebs_v
AS SELECT s."Hdr Order Type Name",
    s."Order Number",
    s."Line Number",
    s."Shipment Number",
    s."Ordered Quantity",
    s."Order Exchange Rate",
    s."Transaction Curr Code",
    s."Cust PO Number",
    s."Request Date",
    s."Ordered Item",
    s."Scheduled Ship Date",
    s."Cancelled Quantity",
    s."Shipped Quantity",
    s."Unit Selling Price",
    s."Actual Ship Date",
    s."Line Order Type",
    s."Line Order Type Name",
    s."Ship From Func Currency",
    s."Curr Exchange Rate",
    s."Extended Price USD",
    s."Order Date",
    s."Booked Date",
    s."Cost of Sale Account",
    s."CREATED_BY_NAME",
    s."Ship From Org Name",
    s."Ship From Org Code",
    s."Bill To Customer Parent",
    s."Bill To Customer Name",
    s."Ship To Customer Parent",
    s."Ship To Customer Name",
    s."Ship From Item Cost LC",
    s."Ship From Item Cost USD",
    s."Extended Price LC",
    s."Sales Rep",
    upper(s."Sales Region"::text) AS "Sales Region",
    s."Hold Type",
    s."Unit Selling PriceLC",
    s."Product Class",
    s."Sales Account",
    s."GL Date",
    s."Invoice Curr Code",
    s."Quantity Credited",
    s."Quantity Invoiced",
    s."SOB Description",
    s."Invoice Period AVG Rate",
    s."Category",
    s."Category Name",
    s."Commodity Class",
    s."Item Description",
    s."Item Name",
    s."Product Family",
    s."Product Line",
    s."Product Model",
    s."Sourcing Segment",
    p.level05_name AS "Label (L5)",
    (p.node::text || ' - '::text) || p.level05_name::text AS "Product Code & Label",
    p.level01_name AS "Segment (L1)",
    p.level03_name AS "Family Segment (L3)",
    p.level02_name AS "Product/Segment (L2)",
    p.level04_name AS "Family Group (L4)",
    s."Common vs System",
    s."Promise Date",
    s."OU",
    COALESCE(btreg.region, bt.region::character varying) AS "Bill To Region",
    COALESCE(streg.region, st.region) AS "Ship To Region",
    COALESCE(streg."Country Code", st.country) AS "Ship To Country",
    s."Bill To Class Code",
    s."Ship To Class Code",
    s."Invoice TRX Number",
    s."Ext Ship From Item Cost LC",
    s."Ext Ship From Item Cost USD",
    TRIM(BOTH FROM COALESCE(mc.mgmt_parent, s."Bill To Customer Name")) AS "MGMT Customer",
    TRIM(BOTH FROM replace(COALESCE(COALESCE(COALESCE(mc.mgmt_region, mo.management_region), streg.region), btreg.region)::text, 'ASIA-'::text, ''::text)) AS "MGMT Region",
    s."Data_Type",
    s."Unit Selling PriceLC" AS "Unit Selling Price LC",
    bt.country AS "Bill To Country",
    e.payment_term_name AS payment_terms,
    COALESCE(st.primary_market_segment, bt.primary_market_segment) AS primary_market_segment,
    COALESCE(st.secondary_market_segment, bt.secondary_market_segment) AS secondary_market_segment,
    0 AS fulfillment_line_number,
    0 AS line_source_number,
    btreg."Mgmt Continent" AS "Bill To Mgmt Continent",
    streg."Mgmt Continent" AS "Ship To Mgmt Continent",
    'EBS Backlog'::text AS "SOURCE_SYSTEM",
    e.line_id,
    e.order_status,
    e.line_status,
    e.fulfill_line_status,
    e.order_creation_date,
    e.line_creation_date,
    e.last_update_date,
    streg.country,
    0 AS "Total_distribution_cost LC",
    edw_prod_dbo.edw_getcostfrozencostperavgusd(f.item_id::bigint, item.default_shipping_org::bigint, CURRENT_DATE, 'EBS'::character varying) AS mfg_frozen_cost_at_per_avg_in_usd,
    edw_prod_dbo.edw_getcostfrozencostplannedusd(f.item_id::bigint, f.ship_from_org_id::bigint, CURRENT_DATE, 'EBS'::character varying) AS mfg_frozen_cost_at_planned_in_usd,
    0 AS "Ship_Frozen_Cost_at_Per_Avg_in_USD"
   FROM stage_bi.fnc_backlog_billing_rpt_vw_mv s
     LEFT JOIN edw_prod_dbo.w_sales_orders_d e ON e.line_id = s."LINE_ID"
     LEFT JOIN edw_prod_dbo.w_sales_orders_f f ON f.line_id = s."LINE_ID"
     LEFT JOIN edw_prod_dbo.w_product_dh p ON p.node::text = s."Product Class"::text
     LEFT JOIN edw_prod_dbo.w_item_org_d item ON item.item_number::character varying(500)::text = s."Item Name"::text AND item.organization_code::text = 'BIM'::text AND item.source_system::text = 'EBS'::text
     LEFT JOIN stage_dbo.bill_to_customer_sites bt ON bt.site_use_id = f.invoice_to_org_id
     LEFT JOIN stage_dbo.ship_to_customer_sites st ON st.site_use_id = f.ship_to_org_id
     LEFT JOIN edw_prod_dbo.country_region streg ON streg.country::text = st.country::text
     LEFT JOIN edw_prod_dbo.country_region btreg ON btreg."Country Code"::text = bt.country::text
     LEFT JOIN edw_prod_dbo.mgmt_cust_pn_lookup mc ON mc."Bill To Customer Name"::text = s."Bill To Customer Name"::text AND mc."Customer PN"::text = s."Ordered Item"::text AND mc."Brooks PN"::text = s."Item Name"::text
     LEFT JOIN edw_prod_dbo.management_override_new mo ON mo.customer_name::text = s."Bill To Customer Name"::text
  WHERE (s."OU"::text <> ALL (ARRAY['BAI'::text, 'BAA'::text, 'BAK'::text, 'BJP'::text, 'BTC'::text, 'BTS'::text, 'BAT'::text, 'BXG'::text, 'BCS'::text, 'BCJ'::text, 'BAS'::text])) AND (s."Line Order Type"::text <> ALL (ARRAY['Invoiced'::text, 'Cancelled'::text]));