-- edw_prod_dbo.bbb_om_table3_ebs_invoc_v source

CREATE OR REPLACE VIEW edw_prod_dbo.bbb_om_table3_ebs_invoc_v
AS SELECT s."Hdr Order Type Name",
    s."Order Number",
    s."Line Number",
    s."Shipment Number",
    s."Ordered Quantity",
    s."Order Exchange Rate",
    s."Transaction Curr Code",
    s."Cust PO Number",
    s."Request Date",
    s."Ordered Item",
    s."Scheduled Ship Date",
    s."Cancelled Quantity",
    s."Shipped Quantity",
    s."Unit Selling Price",
    s."Actual Ship Date",
    s."Line Order Type",
    s."Line Order Type Name",
    s."Ship From Func Currency",
    s."Curr Exchange Rate",
    s."Extended Price USD",
    s."Order Date",
    s."Booked Date",
    s."Cost of Sale Account",
    s."CREATED_BY_NAME",
    s."Ship From Org Name",
    s."Ship From Org Code",
    s."Bill To Customer Parent",
    s."Bill To Customer Name",
    s."Ship To Customer Parent",
    s."Ship To Customer Name",
    s."Ship From Item Cost LC",
    s."Ship From Item Cost USD",
    s."Extended Price LC",
    s."Sales Rep",
    s."Sales Region",
    s."Hold Type",
    s."Unit Selling PriceLC",
    s."Product Class",
    s."Sales Account",
    s."GL Date",
    s."Invoice Curr Code",
    s."Quantity Credited",
    s."Quantity Invoiced",
    s."SOB Description",
    s."Invoice Period AVG Rate",
    s."Category",
    s."Category Name",
    s."Commodity Class",
    s."Item Description",
    s."Item Name",
    s."Product Family",
    s."Product Line",
    s."Product Model",
    s."Sourcing Segment",
    p.level05_name AS "Label (L5)",
    (p.node::text || ' - '::text) || p.level05_name::text AS "Product Code & Label",
    p.level01_name AS "Segment (L1)",
    p.level03_name AS "Family Segment (L3)",
    p.level02_name AS "Product/Segment (L2)",
    p.level04_name AS "Family Group (L4)",
    s."Common vs System",
    s."Promise Date",
    s."OU",
    COALESCE(btreg.region, "BT".region::character varying) AS "Bill To Region",
    COALESCE(streg.region, st.region) AS "Ship To Region",
    COALESCE(streg."Country Code", st.country) AS "Ship To Country",
    "BT".customer_class_code AS "Bill To Class Code",
    s."Ship To Class Code",
    s."Invoice TRX Number",
    s."Ext Ship From Item Cost LC",
    s."Ext Ship From Item Cost USD",
    TRIM(BOTH FROM COALESCE(COALESCE(mc.mgmt_parent, mo.top_level_customer_name), "BT".customer_name)) AS "MGMT Customer",
    TRIM(BOTH FROM replace(COALESCE(COALESCE(COALESCE(mc.mgmt_region, mo.management_region), st.region), "BT".region::character varying)::text, 'ASIA-'::text, ''::text)) AS "MGMT Region",
    s."Data_Type",
    'EBS Invoice'::text AS source_system,
    s."LINE_ID",
    e.order_status,
    e.line_status,
    e.fulfill_line_status,
    e.order_creation_date,
    e.line_creation_date,
    e.last_update_date,
    s."Unit Selling PriceLC" AS "Unit Selling Price LC",
    "BT".country AS "Bill To Country",
    e.payment_term_name AS "PAYMENT_TERMS",
    COALESCE(st.primary_market_segment, "BT".primary_market_segment) AS primary_market_segment,
    COALESCE(st.secondary_market_segment, "BT".secondary_market_segment) AS secondary_market_segment,
    e.ebs_line_id AS fulfillment_line_number,
    btreg."Mgmt Continent" AS "Bill To Mgmt Continent",
    streg."Mgmt Continent" AS "Ship To Mgmt Continent",
    0 AS line_source_number,
    c."Total_distribution_cost LC",
    c.mfg_frozen_cost_at_per_avg_in_usd,
    c.mfg_frozen_cost_at_planned_in_usd,
    c.ship_frozen_cost_at_per_avg_in_usd
   FROM stage_bi.fnc_backlog_billing_rpt_vw_mv s
     JOIN edw_prod_dbo.w_sales_orders_d e ON e.line_id = s."LINE_ID"
     JOIN edw_prod_dbo.w_sales_orders_f f ON f.line_id = s."LINE_ID"
     LEFT JOIN edw_prod_dbo.w_product_dh p ON p.node::text = s."Product Class"::text
     LEFT JOIN stage_dbo.bill_to_customer_sites "BT" ON "BT".site_use_id = f.invoice_to_org_id
     LEFT JOIN stage_dbo.ship_to_customer_sites st ON st.site_use_id = f.ship_to_org_id
     LEFT JOIN edw_prod_dbo.mgmt_cust_pn_lookup mc ON mc."Bill To Customer Name"::text = "BT".customer_name::text AND mc."Customer PN"::text = s."Ordered Item"::text AND mc."Brooks PN"::text = s."Item Name"::text
     LEFT JOIN edw_prod_dbo.management_override_new mo ON mo.customer_name::text = "BT".customer_name::text
     LEFT JOIN edw_prod_dbo.country_region streg ON streg.country::text = st.country::text
     LEFT JOIN edw_prod_dbo.country_region btreg ON btreg."Country Code"::text = "BT".country::text
     LEFT JOIN ( SELECT c_1.so_line_id,
            sum(c_1.total_distribution_cost) AS "Total_distribution_cost LC",
            sum(c_1.mfg_frozen_cost_at_per_avg_in_usd) AS mfg_frozen_cost_at_per_avg_in_usd,
            sum(c_1.mfg_frozen_cost_at_planned_in_usd) AS mfg_frozen_cost_at_planned_in_usd,
            0 AS ship_frozen_cost_at_per_avg_in_usd
           FROM edw_prod_dbo.w_ar_combined_cost c_1
          WHERE c_1.source_system::text = 'EBS'::text AND "right"(c_1.reference_account::text, 4) = '0000'::text
          GROUP BY c_1.so_line_id) c ON f.line_id::double precision = c.so_line_id
  WHERE 1 = 1 AND (s."Line Order Type"::text = 'Invoiced'::text OR s."Line Order Type"::text = 'CANCELLED'::text) AND s."Order Date" > '2021-01-01 00:00:00'::timestamp without time zone AND s."Order Date" < '2024-08-01 00:00:00'::timestamp without time zone
UNION ALL
 SELECT s."Hdr Order Type Name",
    s."Order Number",
    s."Line Number",
    s."Shipment Number",
    s."Ordered Quantity",
    s."Order Exchange Rate",
    s."Transaction Curr Code",
    s."Cust PO Number",
    s."Request Date",
    s."Ordered Item",
    s."Scheduled Ship Date",
    s."Cancelled Quantity",
    s."Shipped Quantity",
    s."Unit Selling Price",
    s."Actual Ship Date",
    s."Line Order Type",
    s."Line Order Type Name",
    s."Ship From Func Currency",
    s."Curr Exchange Rate",
    s."Extended Price USD",
    s."Order Date",
    s."Booked Date",
    s."Cost of Sale Account",
    s."CREATED_BY_NAME",
    s."Ship From Org Name",
    s."Ship From Org Code",
    s."Bill To Customer Parent",
    s."Bill To Customer Name",
    s."Ship To Customer Parent",
    s."Ship To Customer Name",
    s."Ship From Item Cost LC",
    s."Ship From Item Cost USD",
    s."Extended Price LC",
    s."Sales Rep",
    s."Sales Region",
    s."Hold Type",
    s."Unit Selling PriceLC",
    s."Product Class",
    s."Sales Account",
    s."GL Date",
    s."Invoice Curr Code",
    s."Quantity Credited",
    s."Quantity Invoiced",
    s."SOB Description",
    s."Invoice Period AVG Rate",
    s."Category",
    s."Category Name",
    s."Commodity Class",
    s."Item Description",
    s."Item Name",
    s."Product Family",
    s."Product Line",
    s."Product Model",
    s."Sourcing Segment",
    p.level05_name AS "Label (L5)",
    (p.node::text || ' - '::text) || p.level05_name::text AS "Product Code & Label",
    p.level01_name AS "Segment (L1)",
    p.level03_name AS "Family Segment (L3)",
    p.level02_name AS "Product/Segment (L2)",
    p.level04_name AS "Family Group (L4)",
    s."Common vs System",
    s."Promise Date",
    s."OU",
    COALESCE(btreg.region, "BT".region::character varying) AS "Bill To Region",
    COALESCE(streg.region, st.region) AS "Ship To Region",
    COALESCE(streg."Country Code", st.country) AS "Ship To Country",
    s."Bill To Class Code",
    s."Ship To Class Code",
    s."Invoice TRX Number",
    s."Ext Ship From Item Cost LC",
    s."Ext Ship From Item Cost USD",
    TRIM(BOTH FROM COALESCE(COALESCE(mc.mgmt_parent, mo.top_level_customer_name), "BT".customer_name)) AS "MGMT Customer",
    TRIM(BOTH FROM replace(COALESCE(COALESCE(COALESCE(mc.mgmt_region, mo.management_region), st.region), "BT".region::character varying)::text, 'ASIA-'::text, ''::text)) AS "MGMT Region",
    s."Data_Type",
    'EBS Invoice'::text AS source_system,
    s."LINE_ID",
    e.order_status,
    e.line_status,
    e.fulfill_line_status,
    e.order_creation_date,
    e.line_creation_date,
    e.last_update_date,
    s."Unit Selling PriceLC" AS "Unit Selling Price LC",
    "BT".country AS "Bill To Country",
    e.payment_term_name AS "PAYMENT_TERMS",
    COALESCE(st.primary_market_segment, "BT".primary_market_segment) AS primary_market_segment,
    COALESCE(st.secondary_market_segment, "BT".secondary_market_segment) AS secondary_market_segment,
    e.ebs_line_id AS fulfillment_line_number,
    btreg."Mgmt Continent" AS "Bill To Mgmt Continent",
    streg."Mgmt Continent" AS "Ship To Mgmt Continent",
    0 AS line_source_number,
    c."Total_distribution_cost LC",
    c.mfg_frozen_cost_at_per_avg_in_usd,
    c.mfg_frozen_cost_at_planned_in_usd,
    c.ship_frozen_cost_at_per_avg_in_usd
   FROM stage_bi.fnc_backlog_billing_rpt_vw_mv s
     JOIN edw_prod_dbo.w_sales_orders_d e ON e.line_id = s."LINE_ID"
     JOIN edw_prod_dbo.w_sales_orders_f f ON f.line_id = s."LINE_ID"
     LEFT JOIN edw_prod_dbo.w_product_dh p ON p.node::text = s."Product Class"::text
     LEFT JOIN stage_dbo.bill_to_customer_sites "BT" ON "BT".site_use_id = f.invoice_to_org_id
     LEFT JOIN stage_dbo.ship_to_customer_sites st ON st.site_use_id = f.ship_to_org_id
     LEFT JOIN edw_prod_dbo.mgmt_cust_pn_lookup mc ON mc."Bill To Customer Name"::text = "BT".customer_name::text AND mc."Customer PN"::text = s."Ordered Item"::text AND mc."Brooks PN"::text = s."Item Name"::text
     LEFT JOIN edw_prod_dbo.management_override_new mo ON mo.customer_name::text = "BT".customer_name::text
     LEFT JOIN edw_prod_dbo.country_region streg ON streg.country::text = st.country::text
     LEFT JOIN edw_prod_dbo.country_region btreg ON btreg."Country Code"::text = "BT".country::text
     LEFT JOIN ( SELECT c_1.so_line_id,
            sum(c_1.total_distribution_cost) AS "Total_distribution_cost LC",
            sum(c_1.mfg_frozen_cost_at_per_avg_in_usd) AS mfg_frozen_cost_at_per_avg_in_usd,
            sum(c_1.mfg_frozen_cost_at_planned_in_usd) AS mfg_frozen_cost_at_planned_in_usd,
            0 AS ship_frozen_cost_at_per_avg_in_usd
           FROM edw_prod_dbo.w_ar_combined_cost c_1
          WHERE c_1.source_system::text = 'EBS'::text AND "right"(c_1.reference_account::text, 4) = '0000'::text
          GROUP BY c_1.so_line_id) c ON f.line_id::double precision = c.so_line_id
  WHERE 1 = 1 AND (s."Line Order Type"::text = ANY (ARRAY['Invoiced'::text, 'CANCELLED'::text])) AND ((s."OU"::text <> ALL (ARRAY['BAI'::text::character varying, 'BAA'::text::character varying, 'BAK'::text::character varying]::text[])) AND s."Order Date" > '2024-07-31 00:00:00'::timestamp without time zone OR (s."OU"::text <> ALL (ARRAY['BJP'::text::character varying, 'BTC'::text::character varying, 'BTS'::text::character varying, 'BAT'::text::character varying, 'BXG'::text::character varying, 'BCS'::text::character varying, 'BCJ'::text::character varying, 'BAS'::text::character varying]::text[])) AND s."Order Date" > '2025-10-08 00:00:00'::timestamp without time zone);