USE [EDW_PROD]
GO

/****** Object:  StoredProcedure [dbo].[GenerateOCCostsData]    Script Date: 12/10/2025 9:50:52 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--EXEC  [dbo].[GenerateOCCostsData] 
CREATE PROCEDURE [dbo].[GenerateOCCostsData] 
AS
BEGIN
DECLARE @BatchSize INT = 100000;  -- Number of records to delete in each batch
DECLARE @RowsAffected INT = 1; 
--
WHILE (@RowsAffected > 0)
	BEGIN
	--
		DELETE TOP (@BatchSize) FROM w_item_costs_f WHERE source_system = 'OC';
		SET @RowsAffected = @@ROWCOUNT;
	END;
--
	WITH COST_ELEMENTS AS (SELECT CSCD.STD_COST_DETAIL_ID, CSCD.STD_COST_ID, CSCD.CREATION_DATE, CSCD.LAST_UPDATE_DATE,
                                 isnull(cast(CSCD.UNIT_COST as FLOAT),0) UNIT_COST,
                                 CCE.COSTELEMENTBPEOCOSTELEMENTCODE COST_ELEMENT_CODE
                            FROM oc_prod.dbo.CST_STD_COST_DETAILS CSCD, oc_prod.dbo.CST_COST_ELEMENTS_B CCE
                            WHERE CSCD.COST_ELEMENT_ID = CCE.COSTELEMENTBPEOCOSTELEMENTID
                            AND CAST(ISNULL(CSCD.UNIT_COST,'0') AS FLOAT) <> 0 ),
        details as (SELECT CE.STD_COST_DETAIL_ID, 
                        CVUB.INV_ORG_CODE,
                        CAST(IOP.ORGANIZATIONID AS BIGINT) ORGANIZATION_ID,
                        CSC.INVENTORY_ITEM_ID,
                        cast(CSC.TOTAL_COST as FLOAT) TOTAL_COST,
                        cast(CE.UNIT_COST as FLOAT) UNIT_COST,
                        CE.COST_ELEMENT_CODE,
                        CAST(CSC.EFFECTIVE_START_DATE AS  DATE) EFFECTIVE_START_DATE,
                        CAST(isnull(CSC.EFFECTIVE_END_DATE,'9999-12-31') AS DATE) AS EFFECTIVE_END_DATE,
                        CAST(CE.CREATION_DATE AS DATE)  CREATION_DATE, 
                        CAST(CE.LAST_UPDATE_DATE AS DATE)  LAST_UPDATE_DATE  
                        FROM oc_prod.dbo.CST_STD_COSTS CSC,
                        COST_ELEMENTS CE,
                        oc_prod.dbo.INV_ORG_PARAMETERS IOP,
                        (SELECT CVUC.INV_ORG_CODE AS INV_ORG_CODE
                               ,CVUB.COST_ORG_ID
                               ,CVUB.COST_BOOK_ID
                               ,CVUB.VAL_UNIT_ID
                        FROM oc_prod.dbo.CST_VAL_UNITS_B CVUB,
                             oc_prod.dbo.CST_VAL_UNIT_DETAILS CVUD,
                             oc_prod.dbo.CST_VAL_UNIT_COMBINATIONS CVUC
                        WHERE CVUB.COST_BOOK_ID = CVUD.COST_BOOK_ID
                        AND CVUB.VAL_UNIT_ID = CVUD.VAL_UNIT_ID
                        AND CVUC.VAL_UNIT_COMBINATION_ID = CVUD.VAL_UNIT_COMBINATION_ID
                        AND EXISTS (SELECT 1 
                                    FROM oc_prod.dbo.CST_VAL_STRUCTURES_B CVSB
                                    WHERE CVSB.VAL_STRUCTURE_ID = CVUB.VAL_STRUCTURE_ID
                                      AND CVSB.VAL_STRUCTURE_TYPE_CODE = 'ASSET')) CVUB
                        WHERE CSC.VAL_UNIT_ID = CVUB.VAL_UNIT_ID
                        AND CE.STD_COST_ID = CSC.STD_COST_ID
                        AND IOP.ORGANIZATIONCODE = CVUB.INV_ORG_CODE
                        AND csc.status_code = 'PUBLISHED')  
	 INSERT INTO edw_prod.dbo.W_ITEM_COSTS_F (ID, INVENTORY_ITEM_ID, ORGANIZATION_ID, ITEM_STANDARD_COST, MATERIAL_COST, MATERIAL_OVERHEAD_COST, RESOURCE_COST, OVERHEAD_COST, 
	                             OUTSIDE_PROCESSING_COST, LAST_UPDATED, CREATE_DATE, LAST_UPDATE_DATE, CREATION_DATE, SOURCE_SYSTEM, INTEGRATION_ID, STANDARD_COST_REVISION_DATE,
	                             EFFECTIVE_START_DATE, EFFECTIVE_END_DATE )                         
	select  -1, INVENTORY_ITEM_ID, ORGANIZATION_ID, sum(ITEM_STANDARD_COST) ITEM_STANDARD_COST, sum(MATERIAL_COST) MATERIAL_COST, sum(MATERIAL_OVERHEAD_COST) MATERIAL_OVERHEAD_COST, sum(RESOURCE_COST) RESOURCE_COST, sum(OVERHEAD_COST) OVERHEAD_COST, sum(OUTSIDE_PROCESSING_COST) OUTSIDE_PROCESSING_COST, 
	        GETDATE() LAST_UPDATED,GETDATE()  CREATE_DATE, LAST_UPDATE_DATE, CREATION_DATE, 'OC' SOURCE_SYSTEM, CAST(INVENTORY_ITEM_ID AS VARCHAR(40)) + '~' + CAST(ORGANIZATION_ID AS VARCHAR(40))+'~OC' INTEGRATION_ID, EFFECTIVE_END_DATE,
	        EFFECTIVE_START_DATE,EFFECTIVE_END_DATE
	         From (
	select distinct INVENTORY_ITEM_ID, ORGANIZATION_ID, ISNULL(TOTAL_COST,0.0) ITEM_STANDARD_COST, 0.0 MATERIAL_COST, 0.0 MATERIAL_OVERHEAD_COST, 0.0 RESOURCE_COST, 0.0 OVERHEAD_COST, 0.0 OUTSIDE_PROCESSING_COST, LAST_UPDATE_DATE, CREATION_DATE, EFFECTIVE_END_DATE, EFFECTIVE_START_DATE  From details
	Union all
	select INVENTORY_ITEM_ID, ORGANIZATION_ID, 0  ITEM_STANDARD_COST, UNIT_COST MATERIAL_COST, 0 MATERIAL_OVERHEAD_COST, 0 RESOURCE_COST, 0 OVERHEAD_COST, 0 OUTSIDE_PROCESSING_COST, LAST_UPDATE_DATE, CREATION_DATE, EFFECTIVE_END_DATE, EFFECTIVE_START_DATE  From details where COST_ELEMENT_CODE = 'Material'
	Union all
	select INVENTORY_ITEM_ID, ORGANIZATION_ID, 0  ITEM_STANDARD_COST, 0 MATERIAL_COST, UNIT_COST MATERIAL_OVERHEAD_COST, 0 RESOURCE_COST, 0 OVERHEAD_COST, 0 OUTSIDE_PROCESSING_COST, LAST_UPDATE_DATE, CREATION_DATE, EFFECTIVE_END_DATE, EFFECTIVE_START_DATE  From details where COST_ELEMENT_CODE = 'Material Overhead'
	Union all
	select INVENTORY_ITEM_ID, ORGANIZATION_ID, 0  ITEM_STANDARD_COST, 0 MATERIAL_COST, 0 MATERIAL_OVERHEAD_COST, UNIT_COST RESOURCE_COST, 0 OVERHEAD_COST, 0 OUTSIDE_PROCESSING_COST, LAST_UPDATE_DATE, CREATION_DATE, EFFECTIVE_END_DATE, EFFECTIVE_START_DATE  From details where COST_ELEMENT_CODE = 'Resource'
	Union all
	select INVENTORY_ITEM_ID, ORGANIZATION_ID, 0  ITEM_STANDARD_COST, 0 MATERIAL_COST, 0 MATERIAL_OVERHEAD_COST, 0 RESOURCE_COST, UNIT_COST OVERHEAD_COST, 0 OUTSIDE_PROCESSING_COST, LAST_UPDATE_DATE, CREATION_DATE, EFFECTIVE_END_DATE, EFFECTIVE_START_DATE  From details where COST_ELEMENT_CODE = 'Overhead'
	Union all
	select INVENTORY_ITEM_ID, ORGANIZATION_ID, 0  ITEM_STANDARD_COST, 0 MATERIAL_COST, 0 MATERIAL_OVERHEAD_COST, 0 RESOURCE_COST, 0 OVERHEAD_COST, UNIT_COST OUTSIDE_PROCESSING_COST, LAST_UPDATE_DATE, CREATION_DATE, EFFECTIVE_END_DATE, EFFECTIVE_START_DATE  From details where COST_ELEMENT_CODE = 'Outside Processing') D
	group by INVENTORY_ITEM_ID, ORGANIZATION_ID,LAST_UPDATE_DATE, CREATION_DATE, EFFECTIVE_END_DATE , EFFECTIVE_START_DATE;
--
update w_item_costs_f set effective_end_dATE = '2024-08-29' where inventory_item_id = 100000099129079 and organization_id = 300000004007248 and effective_start_date = '1900-01-01';
END;

GO



